FROM python:3.12-slim

# Tkinter + polices + X11
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-tk \
    tk-dev \
    libx11-6 \
    libxft2 \
    fonts-dejavu-core \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir websockets pillow

WORKDIR /app

COPY game/  game/
COPY network/ network/
COPY ui/    ui/

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "ui.app"]
